import Header from "./(useClient)/Header";
import Logo from "./(useClient)/Logo";
import Navigation from "./(useClient)/Navigation";
import Search from "./(useClient)/Search";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-7xl mx-auto h-screen space-y-8 pt-24 px-2">
          <div className="flex justify-between items-center">
            <Navigation />
            <Logo />
            <Search />
          </div>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
