import Navigation from "./(useClient)/Navigation";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./(useClient)/Navigation/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={inter.className} lang="en">
      <body className="bg-slate-300 mx-6 m-3 lg:mx-12 lg:p-6">
        <div className="flex max-w-7xl mx-auto space-x-2 items-center mt-4">
          <Navigation />
        </div>
        <Header />
        <div className="p-5 mt-8 lg:mt-32 bg-slate-200 max-w-7xl min-h-screen mx-auto rounded-lg">
          {children}
        </div>
      </body>
    </html>
  );
}
